server:
  port: ${LAB_RESULTS_OUTBOUND_SERVER_PORT}

logging:
  level:
    uk.nhs.digital.nhsconnect.lab.results: ${LAB_RESULTS_LOGGING_LEVEL}
  pattern:
    console: "-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} ConversationId=%X{ConversationId} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics
  health:
    mongo:
      enabled: true

spring:
  jms:
    listener:
      acknowledge-mode: CLIENT

labresults:
  amqp:
    brokers: ${LAB_RESULTS_AMQP_BROKERS}
    meshOutboundQueueName: ${LAB_RESULTS_MESH_OUTBOUND_QUEUE_NAME}
    meshInboundQueueName: ${LAB_RESULTS_MESH_INBOUND_QUEUE_NAME}
    gpOutboundQueueName: ${LAB_RESULTS_GP_OUTBOUND_QUEUE_NAME}
    exchange: amq.direct
    username: ${LAB_RESULTS_AMQP_USERNAME}
    password: ${LAB_RESULTS_AMQP_PASSWORD}
    maxRedeliveries: ${LAB_RESULTS_AMQP_MAX_REDELIVERIES}
  mongodb:
    uri: ${LAB_RESULTS_MONGO_URI}
    database: ${LAB_RESULTS_MONGO_DATABASE_NAME}
    host: ${LAB_RESULTS_MONGO_HOST}
    port: ${LAB_RESULTS_MONGO_PORT}
    username: ${LAB_RESULTS_MONGO_USERNAME}
    password: ${LAB_RESULTS_MONGO_PASSWORD}
    options: ${LAB_RESULTS_MONGO_OPTIONS}
    autoIndexCreation: ${LAB_RESULTS_MONGO_AUTO_INDEX_CREATION}
    ttl: ${LAB_RESULTS_MONGO_TTL}
    cosmosDbEnabled: ${LAB_RESULTS_COSMOS_DB_ENABLED}
  mesh:
    mailboxId: ${LAB_RESULTS_MESH_MAILBOX_ID}
    mailboxPassword: ${LAB_RESULTS_MESH_MAILBOX_PASSWORD}
    sharedKey: ${LAB_RESULTS_MESH_SHARED_KEY}
    host: ${LAB_RESULTS_MESH_HOST}
    certValidation: ${LAB_RESULTS_MESH_CERT_VALIDATION}
    endpointCert: ${LAB_RESULTS_MESH_ENDPOINT_CERT}
    endpointPrivateKey: ${LAB_RESULTS_MESH_ENDPOINT_PRIVATE_KEY}
    subCAcert: ${LAB_RESULTS_MESH_SUB_CA}
    recipientToMailboxIdMappings: ${LAB_RESULTS_MESH_RECIPIENT_MAILBOX_ID_MAPPINGS}
    wakeupIntervalInMilliseconds: ${LAB_RESULTS_MESH_CLIENT_WAKEUP_INTERVAL_IN_MILLISECONDS}
    pollingCycleMinimumIntervalInSeconds: ${LAB_RESULTS_MESH_POLLING_CYCLE_MINIMUM_INTERVAL_IN_SECONDS}
    pollingCycleDurationInSeconds: ${LAB_RESULTS_MESH_POLLING_CYCLE_DURATION_IN_SECONDS}
  scheduler:
    enabled: ${LAB_RESULTS_SCHEDULER_ENABLED}