name: "Build"
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: "Tests"
    uses: ./.github/workflows/test.yml
    with:
      name: Lab Results Adaptor
      path: ./
    secrets: inherit

