name: PR Quality Check
on: pull_request
jobs:
  check-pr-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check ticket name conforms to requirements
        run: echo ${{ github.event.pull_request.title }} | grep -i -E -q "((apm|niad)-[0-9]+)|(dependabot\/)"

  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name confirms to requirements
        run: echo ${{ github.event.pull_request.head.ref }} | grep -i -E -q "(((feature|bug))/(niad)-[0-9]+-[a-zA-Z]+)"
