name: PR Quality Check
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  check-pr-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check ticket name conforms to requirements
        run: 'echo ${{ github.event.pull_request.title }} | grep -i -E -q "^niad-[0-9]+: [a-z]+"'

  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name conforms to requirements
        run: 'echo ${{ github.event.pull_request.head.ref }} | grep -i -E -q "^(feature|task|bug|hotfix)\/niad-[0-9]+(-[a-z]+)+"'
