on:
  release:
    types: [published]

jobs:
  push_to_dockerhub:
    strategy:
      matrix:
        config:
          - folder: src
            dockerhub_name: nia-lab-results-adaptor
            upload_url: ${{ github.event.release.upload_url }}
    uses: NHSDigital/integration-adaptor-actions/.github/workflows/release-adaptor-container-image.yml@main
    with:
        folder: ${{ matrix.config.folder }}
        dockerhub_name: ${{ matrix.config.dockerhub_name }}
        upload_url: ${{ matrix.config.upload_url }}
    secrets: inherit
